#!/bin/bash
#
# Avoid: "pyenv-virtualenv: prompt changing will be removed from future release."
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

#
# Fixups for Bivio environment running in terminado.
#
# We don't want PROMPT_COMMAND for anything
unset PROMPT_COMMAND
if [[ -n $PS1 ]]; then
    export PS1='\W$ '
    export TERM=xterm
fi

# Workaround $PYENV_VERSION being set in
# radiasoft/containers/radiasoft/beamsim-jupyter/radia-run.sh
#TODO(robnagler) Need to find a cleaner fix, which will start
# terminado without $PYENV_VERSION.
if [[ $JPY_USER && $PYENV_VERSION && -z $RS_TERMINADO_INIT ]]; then
    export RS_TERMINADO_INIT=1
    pyenv deactivate >&/dev/null || true
    unset PYENV_VERSION PYENV_VIRTUAL_ENV VIRTUAL_ENV
fi
